# Generated by Django 4.1 on 2022-08-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factory_name', models.CharField(max_length=200)),
                ('Product_name', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
