# Generated by Django 4.1 on 2022-09-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
        ('product', '0006_factory_alter_product_factory_name'),
    ]

    operations = [
    ]
